### ISSUE TITLE
Obfuscater Nuxt Build Error: v-for has invalid expression.    

### ISSUE THREAD

**Issue by jrvaroni** [jd1378/nuxt-obfuscator#3]
I'm trying to implement the obfuscator in my project, but it is converting the expressions in my v-for:

` <div v-for="(item, index) kbiquzn variable" :key="index"></div>`

it is giving replace in the expression "in" replacing it with "kbiquzn"

**Comment by jd1378** [comment]
This obfuscator is hard to pull off right to be honest
The way it works is basically it tries to replace all class names it detects between **any** quotes
Meaning if you have a class named _in_ , you will have problem

**Comment by jd1378** [comment]
The correct way would have been parsing the entire output html and replacing the class names after render, but im not sure how feasible is that

**Comment by jd1378** [comment]
fixed in [v1.1.5](https://github.com/jd1378/nuxt-obfuscator/releases/tag/v1.1.5)
